---
# tasks file for redhat-cust-portal-auth

# Refresh rh_cust_portal_token; creating an authorized bearer token
- name: Request Red Hat Customer Portal Token
  ansible.builtin.uri:
    url: "{{ auth_api_baseurl }}"
    method: POST
    return_content: true
    body_format: form-urlencoded
    headers:
      accept: application/json
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ rh_cust_portal_token }}"
  run_once: true
  register: token

# Define access_token variable
- name: Set Fact - access_token
  ansible.builtin.set_fact:
    access_token: "{{ token['json']['access_token'] }}"
