---
# defaults file for redhat-cust-portal-create-case
api_baseurl: https://api.access.redhat.com/support/
api_endpoint: v1/cases
api_request_url: "{{ api_baseurl }}/{{ api_endpoint }}"

case_product: "OpenShift Container Platform"
case_product_version: "4.13"
case_summary: "Test Case"
case_description: "This is a test"
case_severity: "4 (Low)"
# Case Severity Options
# 4 (Low)
# 3 (Normal)
# 2 (High)
# 1 (Urgent)
...
