---
- name: Create Support Case on Red Hat Customer Portal for OpenShift Issue
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/redhat-customer-portal-token.yml
    - vars/cluster-information.yml
