---
- name: Create Support Case on Red Hat Customer Portal
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/redhat-customer-portal-token.yml

  tasks:
    - name: "[INCLUDE ROLE] - Red Hat Customer Portal Authentication"
      ansible.builtin.include_role:
        name: redhat-customer-portal-authentication

    - name: "[INCLUDE ROLE] - Red Hat Customer Portal Create Case"
      ansible.builtin.include_role:
        name: redhat-customer-portal-create-case
...
