---
- name: Generate OpenShift Must Gather
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/redhat-create-customer-support-case.yml

  tasks:
    - name: Verify Cluster Information is provided
      ansible.builtin.assert:
        that:
          - ocp_cluster_name is defined and ocp_cluster_name | length > 0
          - ocp_base_domain is defined and ocp_base_domain | length > 0
        fail_msg:
          - "Check cluster information is properly provided"
          - '-e "ocp_cluster_name=<cluster_name>"'
          - '-e "ocp_base_domain=<base_domain>"'

    # Check if OpenShift CLI tools are installed
    - name: Check if OC is installed
      block:
        - name: Check for OC installer
          ansible.builtin.stat:
            path: "{{ openshift_client_bin_dir }}/oc"
          register: oc_install

        # Install OpenShift CLI tools if the oc command is not found in /usr/local/bin/
        - name: "[INCLUDE ROLE] - Red Hat OpenShift Client Tools Install"
          ansible.builtin.include_role:
            name: redhat-openshift-client-tools-install
          when: not oc_install['stat']['exists']

    - name: "[INCLUDE ROLE] - Red Hat OpenShift Validate Kube Config"
      ansible.builtin.include_role:
        name: redhat-openshift-validate-kube-config

    - name: "[INCLUDE ROLE] - Red Hat OpenShift Cluster Information"
      ansible.builtin.include_role:
        name: redhat-openshift-cluster-information

    - name: "[INCLUDE ROLE] - Red Hat OpenShift Generate Must Gather"
      ansible.builtin.include_role:
        name: redhat-openshift-generate-must-gather
...
