---
- name: Add Comment on Support Case on Red Hat Customer Portal
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/redhat-create-customer-support-case.yml
    - vars/redhat-customer-portal-token.yml

  tasks:
    - name: "[INCLUDE ROLE] - Red Hat Customer Portal Authentication"
      ansible.builtin.include_role:
        name: redhat-customer-portal-authentication

    # - name: "[INCLUDE ROLE] - Red Hat Customer Portal Get Current User"
    #   ansible.builtin.include_role:
    #     name: redhat-customer-portal-get-current-user

    - name: "[INCLUDE ROLE] - Red Hat Customer Portal Add Case Comment"
      ansible.builtin.include_role:
        name: redhat-customer-portal-add-case-comment
...
