---
- name: Get Current Logged-In User on Red Hat Customer Portal
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/redhat-customer-portal-token.yml

  tasks:
    - name: "[INCLUDE ROLE] - Red Hat Customer Portal Auth"
      ansible.builtin.include_role:
        name: redhat-customer-portal-auth

    - name: "[INCLUDE ROLE] - Red Hat Customer Portal List Current User"
      ansible.builtin.include_role:
        name: redhat-customer-portal-list-current-user
...
