---
# Add comment to case
- name: Add comment to case on Red Hat Customer Portal
  ansible.builtin.uri:
    url: "{{ api_request_url }}"
    method: POST
    headers:
      accept: application/json
      Authorization: "Bearer {{ access_token }}"
    body_format: json
    body:
      caseNumber: "{{ case_number }}"
      commentBody: "{{ case_comment }}"
      contentType: "plaintext"
    status_code: [200, 201]
    return_content: true
  run_once: true
  register: add_case_comment_result

# Print add_case_comment_results variable
- name: Print Add Case Comment Results
  ansible.builtin.debug:
    var: add_case_comment_result['json']
