---
# tasks file for redhat-openshift-generate-must-gather
# Generate must-gather for cluster using 'oc adm must-gather' command
- name: Generate must-gather
  block:

    # Collect date and time from localhost to add to the output of the must-gather filename
    - name: Get date and time for timestamp
      ansible.builtin.setup:
        gather_subset:
          - date_time

    # Set must-gather directory variable. This is defined with a timestamp.
    - name: Set must-gather destination directory
      ansible.builtin.set_fact:
        must_gather_dir: "/tmp/must-gather.local.{{ ansible_date_time['iso8601_basic'] }}"

    # Generate must-gather using 'oc adm must-gather' command. Had to utilize the shell
    # module in order to execute the 'oc' command.
    - name: Generate Cluster must-gather
      ansible.builtin.shell:
        cmd: "oc adm must-gather --dest-dir {{ must_gather_dir }}"
      register: must_gather_results

    # Display must-gather results for output
    - name: Print must-gather results
      ansible.builtin.debug:
        msg: "{{ must_gather_results['stdout_lines'] }}"

    # Archive must-gather directory into a tar.gz file
    - name: Archive must-gather directory
      ansible.builtin.archive:
        path: "{{ must_gather_dir }}"
        dest: "/tmp/must-gather-{{ ansible_date_time['iso8601_basic'] }}.tar.gz"
        format: gz
        force_archive: true
        mode: "0644"

    # Set must-gather.tar.gz filename variable
    - name: Set fact for must-gather.tar.gz
      ansible.builtin.set_fact:
        must_gather_filename: "/tmp/must-gather-{{ ansible_date_time['iso8601_basic'] }}.tar.gz"
    
    # Set must-gather.tar.gz filename variable for Red Hat Customer Support Attachment
    - name: Set fact for must-gather.tar.gz attachment filename for Red Hat Customer Support Attachment
      ansible.builtin.set_fact:
        redhat_customer_support_attach_file: "{{ must_gather_filename }}"

    # Display must-gather.tar.gz filename location
    - name: Print must-gather.tar.gz file location
      ansible.builtin.debug:
        msg: "{{ must_gather_filename }}"
...
