---
#Create case on Red Hat Customer Portal
- name: Create case on Red Hat Customer Portal
  ansible.builtin.uri:
    url: "{{ api_request_url }}"
    method: POST
    headers:
      accept: application/json
      Authorization: "Bearer {{ access_token }}"
    body_format: json
    body:
      product: "{{ redhat_case_product }}"
      version: "{{ redhat_case_product_version }}"
      summary: "{{ redhat_case_summary }}"
      description: "{{ redhat_case_description }}"
      severity: "{{ redhat_case_severity }}"
      openshiftClusterID: "{{ ocp_cluster_id }}"
      openshiftClusterVersion: "{{ ocp_cluster_version }}"
    status_code: [200, 201]
    return_content: true
  run_once: true
  register: create_case_result

# - name: Print Create Case Result
#   ansible.builtin.debug:
#     var: create_case_result

# Set Red Hat Customer Support Case Number variable
- name: Set redhat_customer_support_case_number fact
  ansible.builtin.set_fact:
    redhat_customer_support_case_number: "{{ create_case_result['json']['location'] | regex_findall('.*/([0-9]+)') | first }}"

# Print redhat_customer_support_case_number variable
- name: Print Case Number
  ansible.builtin.debug:
    var: redhat_customer_support_case_number
