---
- name: Get API Token from OCP Cluster
  community.okd.openshift_auth:
    host: "{{ host_api_url }}"
    username: "{{ ocp_cluster_username }}"
    password: "{{ ocp_cluster_password }}"
    validate_certs: false
  register: ocp_auth

- name: Assert authentication
  ansible.builtin.assert:
    that: ocp_auth['openshift_auth']['api_key'] is defined
...
