---
# tasks file for redhat-customer-portal-list-case-files
# Check if redhat_customer_support_case_number is defined
- name: Check if redhat_customer_support_case_number variable is defined and length > 0
  ansible.builtin.assert:
    that:
      - redhat_customer_support_case_number is defined and redhat_customer_support_case_number | length > 0
    fail_msg:
      - "Red Hat Customer Support case number not provided."
      - "-e 'redhat_customer_support_case_number=<case number>'"

# - name: Attach file to Red Hat Customer Support case {{ redhat_customer_support_case_number }}
#   ansible.builtin.uri:
#     url: "{{ api_request_url }}"
#     method: POST
#     headers:
#       accept: application/json
#       Authorization: "Bearer {{ access_token }}"
#     body_format: json
#     body:
#       caseNumber: "{{ redhat_customer_support_case_number }}"
#       fileName: "{{ redhat_customer_support_attach_file }}"
#     status_code: [200, 201]
#     return_content: true
#   run_once: true
#   register: add_file_to_case_results

# # Print add_file_to_case_results variable
# - name: Print Add File to Case Results
#   ansible.builtin.debug:
#     var: add_file_to_case_results['json']


- name: List attachments on Red Hat Customer Support case {{ redhat_customer_support_case_number }}
  ansible.builtin.uri:
    url: "{{ api_request_url }}"
    method: GET
    return_content: true
    headers:
      accept: application/json
      Authorization: "Bearer {{ access_token }}"
  run_once: true
  register: case_attachements_result

# Print case_attachements_result variable
- name: Print Red Hat Customer Support Case Attachments
  ansible.builtin.debug:
    var: case_attachements_result
