---
# Add users to case on Red Hat Customer Portal
- name: Add users to case on Red Hat Customer Portal
  ansible.builtin.uri:
    url: "{{ api_request_url }}"
    method: POST
    headers:
      accept: application/json
      Authorization: "Bearer {{ access_token }}"
    body_format: json
    body:
      ssoUsername: "{{ item }}"    
    status_code: [200, 201]
    return_content: true
  loop: "{{ case_notify_users }}"
  run_once: true
  register: case_notify_users_result


# - name: Set case_number fact
#   ansible.builtin.set_fact:
#     case_number: "{{ create_case_result['json']['location'] | regex_findall('.*/([0-9]+)') }}"

# # Print case_number variable
# - name: Print Case Number
#   ansible.builtin.debug:
#     var: case_number