---
# tasks file for redhat-cust-portal-list-case-comments
- name: Request Case Comments
  ansible.builtin.uri:
    url: "{{ api_request_url }}"
    method: GET
    return_content: true
    headers:
      accept: application/json
      Authorization: "Bearer {{ access_token }}"
  run_once: true
  register: list_case_comments_result

# Print current_user variable
- name: Print Case Comments
  ansible.builtin.debug:
    var: list_case_comments_result

# # Set current_user variable
# - name: Set Fact - current_user
#   ansible.builtin.set_fact:
#     current_user: "{{ current_user_result['authenticateduser'] }}"

# # Print current_user variable
# - name: Print Current Red Hat Customer User
#   ansible.builtin.debug:
#     var: current_user