---
# defaults file for redhat-customer-portal-create-case
api_baseurl: https://api.access.redhat.com/support/
api_endpoint: v1/cases
api_request_url: "{{ api_baseurl }}/{{ api_endpoint }}"

redhat_case_product: "OpenShift Container Platform"
redhat_case_product_version: "4.13"
# Red Hat Case Product vesioning only supports Major/Minor. Example: 4.10

redhat_case_summary: "Test Case"
# Red Hat Customer Support Case title

redhat_case_description: "This is a test"
# Red Hat Customer Support Case description

redhat_case_severity: "4 (Low)"
# Case Severity Options
# 4 (Low)
# 3 (Normal)
# 2 (High)
# 1 (Urgent)
...
