---
#Create case on Red Hat Customer Portal
- name: Create case on Red Hat Customer Portal
  ansible.builtin.uri:
    url: "{{ api_request_url }}"
    method: POST
    headers:
      accept: application/json
      Authorization: "Bearer {{ access_token }}"
    body_format: json
    body:
      product: "{{ case_product }}"
      version: "{{ case_product_version }}"
      summary: "{{ case_summary }}"
      description: "{{ case_description }}"
      severity: "{{ case_severity }}"
    status_code: [200, 201]
    return_content: true
  run_once: true
  register: create_case_result

- name: Set case_number fact
  ansible.builtin.set_fact:
    case_number: "{{ create_case_result['json']['location'] | regex_findall('.*/([0-9]+)') }}"

# Print case_number variable
- name: Print Case Number
  ansible.builtin.debug:
    var: case_number
